### GET request to example server
GET http://localhost:19999/

###

POST http://localhost:19999/
Content-Type: application/json

{
  "Funktionsnedsättning": "Astmatiker. Kraftig hosta med segt slem. Störd sömn med frekventa uppvakningar. Andfådd, trött och febril. Spirometri har genomförts med låga resultat. Provtagning visar på höga infektionsvärden.",
  "Aktivitetsbegränsningar": "Inga begränsningar. Bör springa minst 5 mil och hoppa hopprep i två timmar dagligen.",
  "Pågående medicinska behandlingar/åtgärder": "Kortisoninhalator 2x2 och vila i två veckor.",
  "Planerade medicinska behandlingar/åtgärder": "Inga planerade behandlingar i nuläget.",
  "Min bedömning av patientens nedsättning av arbetsförmågan": "100% 2025-01-30 - 2025-02-21"
}